name: hanguiemos_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/user-placeholder.png
    - assets/evento-placeholder.png
