// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GlxJcKN7vwmuaRhJnl0ZsqW3lwr5M-g',
    appId: '1:968337210517:web:e74a59c0272fa7fd61ef9c',
    messagingSenderId: '968337210517',
    projectId: 'hanguiemos-ae6e1',
    authDomain: 'hanguiemos-ae6e1.firebaseapp.com',
    storageBucket: 'hanguiemos-ae6e1.appspot.com',
    measurementId: 'G-YECX2K8LZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7u7cko8gNS-wvZN6TVWJufVXQgwmpmF4',
    appId: '1:968337210517:android:68076930bdf457df61ef9c',
    messagingSenderId: '968337210517',
    projectId: 'hanguiemos-ae6e1',
    storageBucket: 'hanguiemos-ae6e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBweo9UAMoeucP9UIs7TdtPwCxnJ7FsxOo',
    appId: '1:968337210517:ios:a7033b46b8e92c2b61ef9c',
    messagingSenderId: '968337210517',
    projectId: 'hanguiemos-ae6e1',
    storageBucket: 'hanguiemos-ae6e1.appspot.com',
    iosBundleId: 'com.example.hanguiemosFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBweo9UAMoeucP9UIs7TdtPwCxnJ7FsxOo',
    appId: '1:968337210517:ios:a7033b46b8e92c2b61ef9c',
    messagingSenderId: '968337210517',
    projectId: 'hanguiemos-ae6e1',
    storageBucket: 'hanguiemos-ae6e1.appspot.com',
    iosBundleId: 'com.example.hanguiemosFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9GlxJcKN7vwmuaRhJnl0ZsqW3lwr5M-g',
    appId: '1:968337210517:web:cf1f47b9160c456f61ef9c',
    messagingSenderId: '968337210517',
    projectId: 'hanguiemos-ae6e1',
    authDomain: 'hanguiemos-ae6e1.firebaseapp.com',
    storageBucket: 'hanguiemos-ae6e1.appspot.com',
    measurementId: 'G-GDF1V1MCLH',
  );
}
